---
- hosts: localhost
  gather_facts: false
  connection: local

  roles:

    - role: aws

  tasks:
    - name: set project directory
      set_fact:
        project_dir: "/data/work"

    - name: terraform init and apply
      community.general.terraform:
        project_path: "{{project_dir}}"
        state: present
        force_init: true
        get_outputs: yes
      register: tf_out

    - name: Debug outputs (sanity check)
      debug:
        var: tf_out.outputs

    - name: Push terraform outputs to Django
      uri:
        url: "https:///13.48.107.144:8000/api/infra/" 
        method: POST
        headers:
          X-API-Key: "{{ lookup('env', 'DJANGO_API_KEY') }}"
          Content-Type: "application/json"
        body_format: json
        body: >
          {
            "key": "{{ item.key }}",
            "value": {{ item.value.value | to_json }}
          }
        status_code: 201
      loop: "{{ tf_out.outputs | dict2items }}"

 
   
            



