---
- hosts: localhost
  gather_facts: false
  connection: local

  roles:

    - role: aws

  tasks:
    - name: set project directory
      set_fact:
        project_dir: "/data/work"

    - name: terraform init and apply
      community.general.terraform:
        project_path: "{{project_dir}}"
        state: present
        force_init: true
      register: tf_apply

    - name: Get Terraform outputs (JSON)
      command: terraform output -json
      args:
        chdir: "{{ project_dir }}"
      register: tf_out_raw
      changed_when: false 

    - name: Parse Terraform outputs
      set_fact:
        tf_out: "{{ tf_out_raw.stdout | from_json }}"
      when: tf_out_raw.stdout is defined and tf_out_raw.stdout | length > 0

    - name: Debug outputs (sanity check)
      debug:
        var: tf_out
      when: tf_out is defined  

    - name: Push terraform outputs to Django
      uri:
        url: "http://13.48.107.144:8000/api/cloud01/infra/"
        method: POST
        headers:
          X-API-Key: "{{ lookup('env', 'DJANGO_API_KEY') }}"
          Content-Type: "application/json"
        body_format: json
        body:
          job_id: "{{ run_id }}"              
          key: "{{ item.key }}"
          value: "{{ item.value.value }}"
        status_code: [200,201]
      loop: "{{ tf_out | default({}) | dict2items }}"
      when: tf_out is defined

 
   
            



