---
- hosts: localhost
  gather_facts: false
  connection: local

  roles:

    - role: aws

  tasks:
    - name: set project directory
      set_fact:
        project_dir: "/data/work"

    - name: terraform init and apply
      community.general.terraform:
        project_path: "{{project_dir}}"
        state: absent
        force_init: true
      register: plan