---
- hosts: localhost
  gather_facts: false
  connection: local

  roles:
    - role: aws

  tasks:
    - name: Set project directory
      set_fact:
        project_dir: "/data/work"

    - name: Generate a unique run ID for this plan
      set_fact:
        run_id: "{{ lookup('pipe','uuidgen') }}"

    - name: Ensure Terraform is initialized
      command: terraform init -input=false
      args:
        chdir: "{{ project_dir }}"
      register: init_result
      failed_when: init_result.rc != 0
      changed_when: "'Terraform has been successfully initialized!' in init_result.stdout"

    - name: Run Terraform plan
      community.general.terraform:
        project_path: "{{ project_dir }}"
        state: planned
        plan_file: tfplan.out
        force_init: true
      register: plan

    - name: Show Terraform plan text
      command: terraform show -no-color tfplan.out
      args:
        chdir: "{{ project_dir }}"
      register: plan_text
      failed_when: plan_text.rc != 0

    - name: Send Terraform plan to middleware
      uri:
        url: "http://middleware/api/cloud01/terraform/plan/"
        method: POST
        headers:
          X-API-Key: "{{ lookup('env', 'DJANGO_API_KEY') }}"
          Content-Type: "application/json"
        body:
          plan_text: "{{ plan_text.stdout }}"
          job_id: "{{ run_id }}"
        body_format: json
        status_code: 200
        validate_certs: no

  
    - name: Debug info
      debug:
        msg:
          run_id: "{{ run_id }}"
          plan_excerpt: "{{ plan_text.stdout[:200] }}"