---
- hosts: localhost
  gather_facts: false
  connection: local

  roles:

    - role: aws

  tasks:
    - name: set project directory
      set_fact:
        project_dir: "/data/work"

    - name: terraform plan
      community.general.terraform:
        project_path: "{{project_dir}}"
        state: planned
        plan_file: tfplan.out
        force_init: true
      register: plan

    - name: print plan for middleware
      debug:
        msg:
          - "===BEGIN_TERRAFORM_PLAN==="
          - "{{ plan_text.stdout }}"
          - "===END_TERRAFORM_PLAN==="
            