---
- hosts: localhost
  gather_facts: false
  connection: local

  roles:
    - role: aws

  tasks:
    - name: Set project directory
      set_fact:
        project_dir: "/data/work"

    - name: Ensure Terraform is initialized
      command: terraform init -input=false
      args:
        chdir: "{{ project_dir }}"
      register: init_result
      failed_when: init_result.rc != 0
      changed_when: "'Terraform has been successfully initialized!' in init_result.stdout"

    - name: Run Terraform plan
      community.general.terraform:
        project_path: "{{ project_dir }}"
        state: planned
        plan_file: tfplan.out
        force_init: true
      register: plan

    - name: Show Terraform plan text
      command: terraform show -no-color tfplan.out
      args:
        chdir: "{{ project_dir }}"
      register: plan_text
      failed_when: plan_text.rc != 0

    - name: Send Terraform plan stdout to middleware
      uri:
        url: "http://13.48.107.144:8000/api/cloud01/infra/terraform/plan/"
        method: POST
        headers:
          X-API-Key: "{{ lookup('env', 'DJANGO_API_KEY') }}"
          Content-Type: "application/json"
        body: |
          {
            "job_id": "{{ job_id }}",
            "stdout": "{{ terraform_plan.stdout | to_json }}"
          }
        body_format: json
        status_code: 200
        validate_certs: no   