---
- hosts: localhost
  gather_facts: false
  connection: local

  collections:
    - community.general

  roles:

    - role: aws

  tasks:
    - name: set project directory
      set_fact:
        project_dir: "/home/"

    - name: terraform plan block
      community.general.terraform:
            project_path: "{{project_dir}}"
            state: present
            force_init: true
            



