---
- name: aws_hub
  block:
    - name: create vpcs
      template:
        src: hub/vpc.j2
        dest: /data/work/modules/vpc/vpc.tf
    - name: create internet gateways 
      template:
        src: hub/igw.j2
        dest: /data/work/modules/vpc/igw.tf 
    - name: create locals
      template:
        src: hub/locals.j2
        dest: /data/work/locals.tf
    - name: create outputs
      template:
        src: hub/outputs.j2
        dest: /data/work/modules/vpc/outputs.tf
    - name: create route
      template:
        src: hub/route.j2
        dest: /data/work/modules/vpc/route.tf
    - name: create subnets
      template:
        src: hub/subnets.j2
        dest: /data/work/modules/vpc/subnets.tf
    - name: create data
      template:
        src: hub/data.j2
        dest: /data/work/modules/vpc/data.tf
    - name: create variables
      template:
        src: hub/variables.j2
        dest: /data/work/modules/vpc/variables.tf
    - name: create versions
      template:
        src: hub/versions.j2
        dest: /data/work/versions.tf
    - name: create main
      template:
        src: hub/main.j2
        dest: /data/work/main.tf
    

