---

- include: vpcbuild.yml
  with_items: "{{ awx_request }}"
  when: 
  
    - item.tags == "aws_vpc"


- include: user.yml
  with_items: "{{ awx_request }}"
  when: 
  
    - item.tags == "aws_user"

- include: provider.yml

